version: "3"
services:
  web:
    build: .
    image: devto-web:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - elasticsearch
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://devto:devto@db:5432/PracticalDeveloper_development
      ELASTICSEARCH_URL: http://elasticsearch:9200
      REDIS_URL: redis://redis:6379
      REDIS_SESSIONS_URL: redis://redis:6379
      RACK_TIMEOUT_WAIT_TIMEOUT: 10000
      RACK_TIMEOUT_SERVICE_TIMEOUT: 10000
      STATEMENT_TIMEOUT: 10000
    volumes:
      - .:/opt/apps/devto:Z
      - gem_cache:/usr/local/bundle/gems:Z

  webpacker:
    image: devto-web:latest
    depends_on:
      - web
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://devto:devto@db:5432/PracticalDeveloper_development
      ELASTICSEARCH_URL: http://elasticsearch:9200
      REDIS_URL: redis://redis:6379
      REDIS_SESSIONS_URL: redis://redis:6379
      RACK_TIMEOUT_WAIT_TIMEOUT: 10000
      RACK_TIMEOUT_SERVICE_TIMEOUT: 10000
      STATEMENT_TIMEOUT: 10000
    command: ./bin/webpack-dev-server

  sidekiq:
    image: devto-web:latest
    depends_on:
      - web
      - redis
      - db
      - elasticsearch
    environment:
      RAILS_ENV: development
      REDIS_SIDEKIQ_URL: redis://redis:6379
      DATABASE_URL: postgresql://devto:devto@db:5432/PracticalDeveloper_development
      ELASTICSEARCH_URL: http://elasticsearch:9200
    entrypoint: ./scripts/entrypoint.sh
    volumes:
      - .:/opt/apps/devto:Z
      - gem_cache:/usr/local/bundle/gems:Z
    command: bundle exec sidekiq -c 2

  db:
    image: postgres:${POSTGRES_VERSION:-9.6.15-alpine}
    environment:
      POSTGRES_USER: devto
      POSTGRES_PASSWORD: devto
      POSTGRES_DB: PracticalDeveloper_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:Z

  redis:
    image: "redis"
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    environment:
      - cluster.name=devto
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data:Z
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  db_data:
  es_data:
  gem_cache:
